param <- list(standard=list(
        Type='LC-MS/MS',
        findPeak=list(
            method='centWave',
            ppm=5,
            peakwidth=c(7, 25),
            snthresh=10,
            prefilter=c(0, 0)
        ),
        retcor=list(
            method='obiwarp',
            plottype='deviation',
            response=1
        ),
        group=list(
            mzwid=0.1,
            bw=10,
            minfrac=0.05
        ),
        annotate=list(
            polarity='positive'
        ),
		MSGFplus=list(
			tolerance='2.5Da',
			tda=TRUE,
			instrument='TOF',
			protease='Unknown',
			lengthRange=c(3,30),
			chargeRange=c(1,3),
			verbose=FALSE
		),
        Complist=list(
            mzwin=0,
            rtwin=0
        )
    ), UPLC.HS=list(
        Type='LC-MS/MS',
        findPeak=list(
            method='centWave',
            ppm=25,
            peakwidth=c(5, 20),
            snthresh=5,
            prefilter=c(1, 3000)
        ),
        retcor=list(
            method='obiwarp',
            plottype='deviation',
            response=10
        ),
        group=list(
            mzwid=0.1,
            bw=1.5,
            minfrac=0.05
        ),
        annotate=list(
            polarity='positive'
        ),
		MSGFplus=list(
				tolerance='2.5Da',
				tda=TRUE,
				instrument='TOF',
				protease='Unknown',
				lengthRange=c(3,30),
				chargeRange=c(1,3),
				verbose=FALSE
		),
        Complist=list(
            mzwin=0,
            rtwin=0
        )
    ), UPLC.HSrtdev=list(
        Type='LC-MS/MS',
        findPeak=list(
            method='centWave',
            ppm=25,
            peakwidth=c(5, 20),
            snthresh=5,
            prefilter=c(1, 3000)
        ),
        retcor=list(
            method='obiwarp',
            plottype='deviation',
            response=10
        ),
        group=list(
            mzwid=0.1,
            bw=1.5,
            minfrac=0.05
        ),
        annotate=list(
            polarity='positive'
        ),
		MSGFplus=list(
				tolerance='2.5Da',
				tda=TRUE,
				instrument='TOF',
				protease='Unknown',
				lengthRange=c(3,30),
				chargeRange=c(1,3),
				verbose=FALSE
		),
        Complist=list(
            mzwin=0,
            rtwin=2
        )
    ), UPLC.MS=list(
        Type='LC-MS/MS',
        findPeak=list(
            method='centWave',
            ppm=25,
            peakwidth=c(5, 20),
            snthresh=5,
            prefilter=c(1, 1000)
        ),
        retcor=list(
            method='obiwarp',
            plottype='deviation',
            response=10
        ),
        group=list(
            mzwid=0.1,
            bw=1.5,
            minfrac=0.05
        ),
        annotate=list(
            polarity='positive'
        ),
		MSGFplus=list(
				tolerance='2.5Da',
				tda=TRUE,
				instrument='TOF',
				protease='Unknown',
				lengthRange=c(3,30),
				chargeRange=c(1,3),
				verbose=FALSE
		),
        Complist=list(
            mzwin=0,
            rtwin=0
        )
    ), UPLC.MSrtdev=list(
        Type='LC-MS/MS',
        findPeak=list(
            method='centWave',
            ppm=25,
            peakwidth=c(5, 20),
            snthresh=5,
            prefilter=c(1, 1000)
        ),
        retcor=list(
            method='obiwarp',
            plottype='deviation',
            response=10
        ),
        group=list(
            mzwid=0.1,
            bw=1.5,
            minfrac=0.05
        ),
        annotate=list(
            polarity='positive'
        ),
		MSGFplus=list(
				tolerance='2.5Da',
				tda=TRUE,
				instrument='TOF',
				protease='Unknown',
				lengthRange=c(3,30),
				chargeRange=c(1,3),
				verbose=FALSE
		),
        Complist=list(
            mzwin=0,
            rtwin=2
        )
    ), UPLC.LS=list(
        Type='LC-MS/MS',
        findPeak=list(
            method='centWave',
            ppm=25,
            peakwidth=c(5, 20),
            snthresh=5,
            prefilter=c(3, 100)
        ),
        retcor=list(
            method='obiwarp',
            plottype='deviation',
            response=10
        ),
        group=list(
            mzwid=0.1,
            bw=1.5,
            minfrac=0.05
        ),
        annotate=list(
            polarity='positive'
        ),
		MSGFplus=list(
				tolerance='2.5Da',
				tda=TRUE,
				instrument='TOF',
				protease='Unknown',
				lengthRange=c(3,30),
				chargeRange=c(1,3),
				verbose=FALSE
		),
        Complist=list(
            mzwin=0,
            rtwin=0
        )
    ), UPLC.LSrtdev=list(
        Type='LC-MS/MS',
        findPeak=list(
            method='centWave',
            ppm=25,
            peakwidth=c(5, 20),
            snthresh=5,
            prefilter=c(3, 100)
        ),
        retcor=list(
            method='obiwarp',
            plottype='deviation',
            response=10
        ),
        group=list(
            mzwid=0.1,
            bw=1.5,
            minfrac=0.05
        ),
        annotate=list(
            polarity='positive'
        ),
		MSGFplus=list(
				tolerance='2.5Da',
				tda=TRUE,
				instrument='TOF',
				protease='Unknown',
				lengthRange=c(3,30),
				chargeRange=c(1,3),
				verbose=FALSE
		),
        Complist=list(
            mzwin=0,
            rtwin=0
        )
    )
)